src/Entity/Categories.php
<?php

namespace App\Entity;

use App\Repository\CategoriesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: CategoriesRepository::class)]
class Categories
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotNull]
    private ?string $Nom = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $create_at = null;

    #[ORM\ManyToMany(targetEntity: Ordinateur::class, mappedBy: 'ordinateurcategory')]
    private Collection $ordinateurs;

    #[ORM\ManyToMany(targetEntity: SmartPhone::class, mappedBy: 'smartPhoneCategorie')]
    private Collection $smartPhones;

    public function __construct()
    {
        $this->ordinateurs = new ArrayCollection();
        $this->smartPhones = new ArrayCollection();
        $this->create_at = new \DateTimeImmutable; }

    public function getId(): ?int
    {return $this->id; }

    public function getNom(): ?string
    {return $this->Nom; }

    public function setNom(string $Nom): static
    { $this->Nom = $Nom;
        return $this; }

    public function getCreateAt(): ?\DateTimeImmutable
    {return $this->create_at;}

    public function setCreateAt(\DateTimeImmutable $create_at): static
    { $this->create_at = $create_at;
       return $this; }

    /**
     * @return Collection<int, Ordinateur>
     */
    public function getOrdinateurs(): Collection
    {
        return $this->ordinateurs;
    }

    public function addOrdinateur(Ordinateur $ordinateur): static
    {
        if (!$this->ordinateurs->contains($ordinateur)) {
            $this->ordinateurs->add($ordinateur);
            $ordinateur->addOrdinateurcategory($this); }
        return $this;}

    public function removeOrdinateur(Ordinateur $ordinateur): static
    {
        if ($this->ordinateurs->removeElement($ordinateur)) {
            $ordinateur->removeOrdinateurcategory($this); }
        return $this;}   

    /** * @return Collection<int, SmartPhone> */
    
    public function getSmartPhones(): Collection
    {
        return $this->smartPhones;}

    public function addSmartPhone(SmartPhone $smartPhone): static
    { if (!$this->smartPhones->contains($smartPhone)) { $this->smartPhones->add($smartPhone); $smartPhone->addSmartPhoneCategorie($this); }
    return $this;}

    public function removeSmartPhone(SmartPhone $smartPhone): static
    {if ($this->smartPhones->removeElement($smartPhone)) { $smartPhone->removeSmartPhoneCategorie($this); }
    return $this;}

    public function __toString()
    { return $this->Nom;}
}

src/Controller/CrudSmartPhoneController.php
<?php

namespace App\Controller;

use App\Entity\SmartPhone;
use App\Form\FormSmartPhoneType;
use App\Repository\SmartPhoneRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CrudSmartPhoneController extends AbstractController
{
    #[Route('/list/smartphone', name: 'app_crud_smart_phone', methods:['GET','POST'])]
    public function index(SmartPhoneRepository $repository, PaginatorInterface $paginator, Request $request ): Response
    {
        $data = $repository->findAll();
        $smartPhone =  $paginator->paginate(
            $data, $request->query->getInt('page', 1),
            10);
        return $this->render('crud_smart_phone/index.html.twig', ['smartPhone'=> $smartPhone]);}

    //  créer un nouveau produits smartphone

    #[Route('/cree/smartphone', name: 'creer_smart_phone', methods:['GET','POST'])]
    public function create( Request $request, EntityManagerInterface $manager): Response
    {
        
        $smartPhone= new SmartPhone();
        // j'ai créé un formulaire
        $formsmartPhone = $this->createForm(FormSmartPhoneType::class, $smartPhone);
         // j'ai tretait la requete de formulaire 
        $formsmartPhone->handleRequest($request);
        if($formsmartPhone->isSubmitted() && $formsmartPhone->isValid()){
           
           $smartPhone= $formsmartPhone->getData();
           $manager->persist($smartPhone);
           
           $manager->flush();
           $this->addFlash(
            'success',
            'votre Produit a été bien rajouté dans le système',
           );
        }
        return $this->render('crud_smart_phone/CreerSmartphones.html.twig', 
        ['formsmartPhone'=>$formsmartPhone->createView(),]);}


     //  modifier produits smartphone

     #[Route('/modifier/smartphone/{id}', name: 'modifier_smart_phone', methods:['GET','POST'])]
     public function edit(SmartPhoneRepository $repository,int $id ,Request $request, 
     EntityManagerInterface $manager ): Response
     {
 
        $smartPhone= $repository->findOneBy(['id'=>$id]);
        $formsmartPhone= $this->createForm(FormSmartPhoneType::class, $smartPhone);
        
        $formsmartPhone->handleRequest($request);
        if($formsmartPhone->isSubmitted() && $formsmartPhone->isValid()){
           $smartPhone =$formsmartPhone->getData();
           $manager->persist($smartPhone);
           $manager->flush();
         
        }
         return $this->render('crud_smart_phone/ModifierSmartphones.html.twig', [
            'formsmartPhone'=>$formsmartPhone->createView(),
             
         ]);
     
     }

     
     //  supprimer produits smartphone

     #[Route('/supprimer/smartphone/{id}', name: 'delete_smart_phone', methods:['GET','POST'])]
     public function delete(SmartPhoneRepository $repository,int $id , 
     EntityManagerInterface $manager ): Response
     {
        $smartPhone= $repository->findOneBy(['id'=>$id]);
        $manager->remove($smartPhone);
        $manager->flush();
        $this->addFlash(
            'success',
            'votre voiture a été bien supprimé dans le système',
        );
        return $this->redirectToRoute('creer_smart_phone');
         
    
 }
        
     
     }

templates/crud_smart_phone/CreerSmartphones.html.twig
{% extends 'base.html.twig' %}

{% block title %}page-crudSmarthphone{% endblock %}

{% block body %}

<div class="container">
<div class="grid">
<h4> formulaire Creation nouveau SmartPhone</h4>

{{ form_start(formsmartPhone) }}


{{ form_end(formsmartPhone) }}
<d/iv>
</div>
{% endblock %}

templates/crud_smart_phone/ModifierSmartphones.html.twig
{% extends 'base.html.twig' %}

{% block title %}page-Modifier{% endblock %}

{% block body %}

<div class="container"> 
<div class="grid">

<h4> formulaire Modifier SmartPhone</h4>

{{ form_start(formsmartPhone)}}


{{ form_end(formsmartPhone)}}

</div>
</div>
{% endblock %}

templates/crud_smart_phone/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}page-crudSmarthphone{% endblock %}

{% block body %}
  <h3 class="text-center">liste des Télephones</h3>
<table class="table text-center  container rounded ">
  <thead >
    <tr>
    <th scope="col">#Id</th>
      <th scope="col">Model de telephone</th>
      <th scope="col">prix</th>
      <th scope="col">photo</th>
     <th scope="col">date de creation</th>
     <th scope="col">Option</th>
    </tr>
  </thead>
  {% for smartPhones in smartPhone %}
  <tbody>
    <tr>
     <td>{{smartPhones.id}}</td>
      <td>{{smartPhones.nom}}</td>
      <td>{{smartPhones.prix | number_format(0,',',)}} €</td>
      <td><img  style ="width:50px"src="{{vich_uploader_asset(smartPhones,'imageFile')}}" class="card-img-top" alt="..."></td>
      <td>Cell</td>
      <td cla="d-flex container">
      <a class="bg-success text-dark p-1 rounded bg-opacity-75 me-1" href="{{path('modifier_smart_phone',{id: smartPhones.id})}}">modifier <i class="fa-regular fa-pen-to-square text-light ms-1"></i></a>
      <a class="bg-danger text-dark p-1 rounded bg-opacity-75 " href="{{path('delete_smart_phone',{id: smartPhones.id})}}">supprimer <i class="fa-solid fa-trash-can text-light ms-1"></i></a>
      <a class="bg-dark text-light p-1 rounded bg-opacity-75 " href="{{path("creer_smart_phone")}}">créer<i class="fa-solid fa-trash-can text-light ms-1"></i></a>
      </td>
    </tr>
   
  </tbody>
  {% endfor %}
</table>

     {# display navigation #}
<div class="navigation d-flex justify-content-center mt-3">
    {{knp_pagination_render(smartPhone)}}
</div>
{% endblock %}