src/Entity/Commentaires.php
<?php

namespace App\Entity;

use App\Repository\CommentairesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentairesRepository::class)]
class Commentaires
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $commentaire = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Note = null;

    #[ORM\OneToMany(mappedBy: 'commentaires', targetEntity: Ordinateur::class)]
    private Collection $commentaireOrdinateur;

    #[ORM\OneToMany(mappedBy: 'commentaires', targetEntity: SmartPhone::class)]
    private Collection $commentaireSmartPhone;

    #[ORM\Column]
    private ?\DateTimeImmutable $create_at = null;

    public function __construct()
    {
        $this->commentaireOrdinateur = new ArrayCollection();
        $this->commentaireSmartPhone = new ArrayCollection();
        $this->create_at= new \DateTimeImmutable;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(string $commentaire): static
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->Note;
    }

    public function setNote(?string $Note): static
    {
        $this->Note = $Note;

        return $this;
    }

    /**
     * @return Collection<int, Ordinateur>
     */
    public function getCommentaireOrdinateur(): Collection
    {
        return $this->commentaireOrdinateur;
    }

    public function addCommentaireOrdinateur(Ordinateur $commentaireOrdinateur): static
    {
        if (!$this->commentaireOrdinateur->contains($commentaireOrdinateur)) {
            $this->commentaireOrdinateur->add($commentaireOrdinateur);
            $commentaireOrdinateur->setCommentaires($this);
        }

        return $this;
    }

    public function removeCommentaireOrdinateur(Ordinateur $commentaireOrdinateur): static
    {
        if ($this->commentaireOrdinateur->removeElement($commentaireOrdinateur)) {
            // set the owning side to null (unless already changed)
            if ($commentaireOrdinateur->getCommentaires() === $this) {
                $commentaireOrdinateur->setCommentaires(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, SmartPhone>
     */
    public function getCommentaireSmartPhone(): Collection
    {
        return $this->commentaireSmartPhone;
    }

    public function addCommentaireSmartPhone(SmartPhone $commentaireSmartPhone): static
    {
        if (!$this->commentaireSmartPhone->contains($commentaireSmartPhone)) {
            $this->commentaireSmartPhone->add($commentaireSmartPhone);
            $commentaireSmartPhone->setCommentaires($this);
        }

        return $this;
    }

    public function removeCommentaireSmartPhone(SmartPhone $commentaireSmartPhone): static
    {
        if ($this->commentaireSmartPhone->removeElement($commentaireSmartPhone)) {
            // set the owning side to null (unless already changed)
            if ($commentaireSmartPhone->getCommentaires() === $this) {
                $commentaireSmartPhone->setCommentaires(null);
            }
        }

        return $this;
    }

    public function getCreateAt(): ?\DateTimeImmutable
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeImmutable $create_at): static
    {
        $this->create_at = $create_at;

        return $this;
    }

   
}

src/Controller/CommentaireProduitsController.php
<?php

namespace App\Controller;

use App\Entity\Commentaires;
use App\Form\FormCommentaireType;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\CommentairesRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CommentaireProduitsController extends AbstractController
{
    //route liste des commentaire
    #[Route('/commentaire/produits', name: 'app_commentaire_produits')]
    public function index(CommentairesRepository $repository, PaginatorInterface $paginator, Request $request): Response
    {
     $data = $repository->findAll();
     $Commentaire= $paginator->paginate(
            $data, $request->query->getInt('page', 1),
            10
        );

        return $this->render('commentaire_produits/index.html.twig', [
           'Commentaire'=> $Commentaire
        ]);
    }

    // supprimer commentaire
    #[Route('/supprimer/commentaire/{id}', name: 'delete_commentaire_produits',methods:['GET'])]
    public function delete(CommentairesRepository $repository,int $id ,EntityManagerInterface $manager ): Response
    {
        $Commentaire = $repository->findOneBy(['id'=> $id]);
        $manager->remove($Commentaire);
        $manager->flush();
    
        return $this->redirectToRoute('app_commentaire_produits');
    }

    //formulaire commentaire clientel
    

     #[Route('/creer/commentaire', name: 'creer_commentaire', methods:['GET','POST'])]
     public function create( Request $request, EntityManagerInterface $manager ): Response
     {
         $Commentaire= new Commentaires();
         $formCommentaire = $this->createForm(FormCommentaireType::class, $Commentaire);
 
         $formCommentaire ->handleRequest($request);
         if($formCommentaire ->isSubmitted() && $formCommentaire ->isValid()){
            $Commentaire= $formCommentaire ->getData();
 
            $manager->persist($Commentaire);
            
            $manager->flush();
         }
         return $this->render('commentaire_produits/formulaire_commentaire.html.twig', [
             'formCommentaire'=> $formCommentaire->createView(),
             'Commentaire'=> $Commentaire
             
         ]);
     
     }
}

templates/commentaire_produits/formulaire_commentaire.html.twig
{% extends 'base.html.twig' %}

{% block title %}page-crudSmarthphone{% endblock %}

{% block body %}

<div class="container  ">
  <h4>POster votre avis </h4>
{{ form_start(formCommentaire) }}

{{ form_row(formCommentaire.commentaire)}}

<div class="d-flex gap-2">
{{ form_row(formCommentaire.Note) }}
{{ form_row(formCommentaire.submit) }}
</div>


{{ form_end(formCommentaire) }}

  
  {{Commentaire.Commentaire}} 
  {{Commentaire.note}}
  

</div>
 
{% endblock %}

templates/commentaire_produits/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}page-crudSmarthphone{% endblock %}

{% block body %}
 
  <h3> liste des commentaires</h3>
 



<table class="table text-center  container rounded ">
 <label for="site-search"></label>
<input  class="barDeRecherche" type="search" id="site-search" name="q" placeholder="recherche..."/><i class="fa-solid fa-magnifying-glass"></i>
  <thead >
    <tr class="">
      <th scope="col">#id</th>
      <th scope="col">Commetaires</th>
      <th scope="col">Note</th>
      <th scope="col">Date</th>
      <th scope="col">Option</th>
    </tr>
  </thead>
  {% for Commentaires in Commentaire %}
  <tbody>
    <tr >
      <td>{{Commentaires.id}}</td>
      <td>{{Commentaires.Commentaire}}</td>
      <td>{{Commentaires.note}}</td>
      <td>{{Commentaires.CreateAT|date("m/d/Y")}}</td>
      <td cla="d-flex container">
      <a class="bg-danger text-dark p-1 rounded bg-opacity-75 " href="{{path('delete_commentaire_produits' ,{id: Commentaires.id})}}">supprimer <i class="fa-solid fa-trash-can text-light ms-1"></i></a>
      </td>
    </tr>
   
  </tbody>
 {% endfor %}
</table>

     {# display navigation #}
<div class="navigation d-flex justify-content-center mt-3">
    {{knp_pagination_render(Commentaire)}}
</div>
{% endblock %}